import fs from "fs";
import path from "path";
import { db } from "../src/db/index.js";
import { fornecedores, pontosFisicos } from "../src/db/schema.js";

// Lista de coordenadas estimadas para bairros e avenidas de Feira de Santana
const geoFeira = {
  "Centro": { lat: -12.2568, lng: -38.9662 },
  "Santa Mônica": { lat: -12.2612, lng: -38.9485 },
  "Capuchinhos": { lat: -12.2645, lng: -38.9550 },
  "SIM": { lat: -12.2680, lng: -38.9220 },
  "Cidade Nova": { lat: -12.2350, lng: -38.9600 },
  "Mangabeira": { lat: -12.2280, lng: -38.9450 },
  "Muchila": { lat: -12.2700, lng: -38.9750 },
  "Parque Getúlio Vargas": { lat: -12.2530, lng: -38.9490 },
  "Lagoa Grande": { lat: -12.2470, lng: -38.9420 },
  "Tomba": { lat: -12.2850, lng: -38.9620 },
  "Queimadinha": { lat: -12.2480, lng: -38.9680 },
  "Vila Olímpia": { lat: -12.2380, lng: -38.9800 },
  "Coronel José Pinto": { lat: -12.2510, lng: -38.9520 },
};

async function seedRealData() {
  console.log("🚀 Iniciando catalogação e integração dos fornecedores reais...");

  // Inserir Fornecedores Oficiais
  const listaFornecedores = [
    {
      id: "FORN-BULLOS",
      nome: "Bullos Outdoor",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Exibidora OOH",
      praca: "Feira de Santana",
      contatoNome: "Danilo Bullos",
      whatsapp: "75991912222",
      email: "contato@bullosoutdoor.com.br",
      prazoEntregaDias: 4,
      specsTecnicas: "Outdoor Lona 9,00 x 3,00m e Papel 32 folhas (Fechamento Bi-semanal)",
      observacoes: "Mais de 25 pontos mapeados em Feira de Santana (Getúlio Vargas, Noide Cerqueira, Anel de Contorno).",
    },
    {
      id: "FORN-VITRINE",
      nome: "Vitrine Outdoor",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Exibidora OOH",
      praca: "Feira de Santana",
      contatoNome: "Nanau",
      whatsapp: "75991912222",
      email: "comercial@vitrineoutdoor.com.br",
      prazoEntregaDias: 4,
      specsTecnicas: "Outdoor Lona 9x3m e Papel | Placas no Boulevard Shopping e Shopping Avenida",
      observacoes: "Tabela oficial: Papel R$ 1.100 a R$ 1.500 | Lona R$ 1.200 a R$ 1.600 por Bi-Semana.",
    },
    {
      id: "FORN-VIA-URBANA",
      nome: "Via Urbana Mídia & LED",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Exibidora OOH / LED",
      praca: "Feira de Santana",
      contatoNome: "Ceciliano",
      whatsapp: "71991729849",
      email: "contato@viaurbana.com.br",
      prazoEntregaDias: 3,
      specsTecnicas: "Outdoors Iluminados 8,85x2,85m e 9x3m | Painéis de LED em Feira e Serrinha",
      observacoes: "Pontos estratégicos no Tomba, Capuchinhos, Cidade Nova, Queimadinha e Serrinha.",
    },
    {
      id: "FORN-HENKLEY",
      nome: "Henkley Publicidade (Telas Indoor)",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Telas Indoor / Mídia Digital Urbana",
      praca: "Feira de Santana",
      contatoNome: "Hudson",
      whatsapp: "75999647868",
      email: "contato@henkley.com.br",
      prazoEntregaDias: 2,
      specsTecnicas: "Rede de 45 Telas em 35 locais | Vídeos até 30s | Loop 20min (3x/hora) | 35.100 inserções/mês",
      observacoes: "Audiência mensal: 418.950 pessoas. Planos: Mensal R$ 1.500 | Semestral R$ 1.100/mês | Anual R$ 1.000/mês.",
    },
    {
      id: "FORN-GIRLAN-LED",
      nome: "Girlan LED & OOH",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "LED / Mobiliário Urbano",
      praca: "Feira de Santana",
      contatoNome: "Girlan Porto",
      whatsapp: "71988288000",
      email: "girlan@girlan.com.br",
      prazoEntregaDias: 1,
      specsTecnicas: "Painéis de LED 6x3m e 5x3m | Mobiliário Urbano Vertical | 810 inserções/dia por cota",
      observacoes: "Circuito Feira de Santana com 8 pontos (F01 a F08).",
    },
    {
      id: "FORN-PRESERV",
      nome: "Preserv Outdoor",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Exibidora OOH",
      praca: "Feira de Santana",
      contatoNome: "Marcos",
      whatsapp: "75981826838",
      email: "marcos@preservoutdoor.com.br",
      prazoEntregaDias: 4,
      specsTecnicas: "Outdoor Lona e Papel 9x3m",
      observacoes: "Parceiro ativo de OOH no interior da Bahia.",
    },
    {
      id: "FORN-ESTACAO",
      nome: "Estação Outdoor",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Exibidora OOH",
      praca: "Feira de Santana",
      contatoNome: "Marilda",
      whatsapp: "75981150845",
      email: "marilda@estacaooutdoor.com.br",
      prazoEntregaDias: 4,
      specsTecnicas: "Outdoor Lona e Papel 9x3m",
      observacoes: "Parceiro ativo de OOH.",
    },
    {
      id: "FORN-TV-SUBAE",
      nome: "TV Subaé (Afiliada TV Globo)",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "TV Aberta",
      praca: "Feira de Santana e Região",
      contatoNome: "Beline / Valéria",
      whatsapp: "7599613436",
      email: "comercial@tvsubae.com.br",
      prazoEntregaDias: 3,
      specsTecnicas: "VT 15s e 30s HD 1080p stereo com claquete oficial",
      observacoes: "Maior alcance regional de TV aberta em Feira e mais de 40 municípios.",
    },
    {
      id: "FORN-JOVEM-PAN",
      nome: "Rádio Jovem Pan / Transbrasil FM",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Rádio",
      praca: "Feira de Santana",
      contatoNome: "Neyde",
      whatsapp: "75991924481",
      email: "comercial@jovempanfsa.com.br",
      prazoEntregaDias: 2,
      specsTecnicas: "Spot 30s WAV 44.1kHz 16-bit",
      observacoes: "Líder em público jovem e vestibulandos (UNEF / UNIFAN).",
    },
    {
      id: "FORN-SOCIEDADE-FM",
      nome: "Rádio Sociedade News FM",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Rádio",
      praca: "Feira de Santana",
      contatoNome: "Danilo Freitas",
      whatsapp: "75992635658",
      email: "comercial@sociedadenews.com.br",
      prazoEntregaDias: 2,
      specsTecnicas: "Spot 30s e Testemunhais ao vivo",
      observacoes: "Alta credibilidade jornalística regional.",
    },
    {
      id: "FORN-ACORDA-CIDADE",
      nome: "Rádio & Portal Acorda Cidade",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Rádio / Portal de Notícias",
      praca: "Feira de Santana",
      contatoNome: "Ivana",
      whatsapp: "75991788637",
      email: "comercial@acordacidade.com.br",
      prazoEntregaDias: 1,
      specsTecnicas: "Spot Rádio 30s + Banners Web (Superbanner 728x90 / Retângulo 300x250)",
      observacoes: "Maior audiência de notícias online e no rádio matinal em FSA.",
    },
    {
      id: "FORN-MARIA-JOAO-BUSDOOR",
      nome: "Maria e João Comunicação (Busdoor)",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Busdoor / Transporte Urbano",
      praca: "Feira de Santana",
      contatoNome: "Fernanda",
      whatsapp: "7532117516",
      email: "contato@mariaejoao.com.br",
      prazoEntregaDias: 5,
      specsTecnicas: "Adesivo Perfurado / Back Bus em frotas municipais",
      observacoes: "Circulação em linhas de alta densidade universitária.",
    },
    {
      id: "FORN-PLAY-COMUNICACAO",
      nome: "Play Comunicação Visual",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Gráfica & Fachadas",
      praca: "Feira de Santana",
      contatoNome: "Fabrício",
      whatsapp: "75991989066",
      email: "fabricio@playcomunicacao.com.br",
      prazoEntregaDias: 3,
      specsTecnicas: "Lonas, banners, adesivos vinílicos, testeiras e sinalização interna",
      observacoes: "Fornecedor homologado para eventos e montagem de stands do Grupo Nobre.",
    },
    {
      id: "FORN-STUDIO-PRAISE",
      nome: "Studio Praise (Produção de Áudio)",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Produtora de Áudio",
      praca: "Feira de Santana",
      contatoNome: "Rafael",
      whatsapp: "75991899399",
      email: "praise@studiopraise.com.br",
      prazoEntregaDias: 1,
      specsTecnicas: "Gravação e masterização de jingles, spots de rádio e locuções",
      observacoes: "Agilidade em prazos urgentes de campanha.",
    },
    {
      id: "FORN-CORUJAS-FILMES",
      nome: "Os Corujas Produtora Audiovisual",
      categoriaGeral: "OFFLINE",
      tipoVeiculo: "Produtora Audiovisual",
      praca: "Feira de Santana",
      contatoNome: "Márcio e Felipe",
      whatsapp: "75991402314",
      email: "contato@oscorujas.com.br",
      prazoEntregaDias: 5,
      specsTecnicas: "Gravação de comerciais de TV, institucionais e captação 4K com drone",
      observacoes: "Produção de filmes de Vestibular e Matrículas da holding.",
    },
    {
      id: "FORN-TRAFEGO-DIGITAL",
      nome: "Alexandre Corrêa (Gestão de Tráfego & Performance)",
      categoriaGeral: "DIGITAL",
      tipoVeiculo: "Meta Ads & Google Ads",
      praca: "Bahia / Nacional",
      contatoNome: "Alexandre Corrêa",
      whatsapp: "71991656776",
      email: "alexandre@trafegogruponobre.com.br",
      prazoEntregaDias: 1,
      specsTecnicas: "Campanhas de Leads, Conversão, YouTube Ads e Remarketing",
      observacoes: "Gestão direta das contas de anúncios de UNEF, UNIFAN e Colégio Nobre.",
    },
  ];

  console.log(`Inserindo ${listaFornecedores.length} fornecedores...`);
  for (const f of listaFornecedores) {
    await db.insert(fornecedores).values(f).onConflictDoUpdate({
      target: fornecedores.id,
      set: f,
    });
  }

  // Inserir Pontos de Outdoor e Telas Reais Mapeadas
  const pontosReais = [
    // BULLOS OUTDOOR
    {
      id: "PONTO-BULLOS-121",
      fornecedorId: "FORN-BULLOS",
      codigoIdentificador: "BULLOS-121",
      nomeLocal: "Av. Getúlio Vargas (Antigo Neus Bar / Ponto Central)",
      tipoFormato: "Outdoor Lona 9x3m",
      praca: "Feira de Santana",
      bairro: "Centro",
      endereco: "Av. Getúlio Vargas, em frente ao Ponto Central de Ônibus",
      latitude: -12.2575,
      longitude: -38.9640,
      fotoLocalUrl: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80",
      statusPonto: "Comprado / Ativo",
      observacoes: "Impacto estimado: 429.337 pessoas por bi-semana. Localização nobre no coração da cidade.",
    },
    {
      id: "PONTO-BULLOS-87",
      fornecedorId: "FORN-BULLOS",
      codigoIdentificador: "BULLOS-87",
      nomeLocal: "Pq. Getúlio Vargas (Rua Itaueira / Posto Cidade)",
      tipoFormato: "Outdoor Lona 9x3m",
      praca: "Feira de Santana",
      bairro: "Parque Getúlio Vargas",
      endereco: "Rua Itaueira, Posto Cidade, sentido Centro",
      latitude: -12.2530,
      longitude: -38.9490,
      fotoLocalUrl: "https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?auto=format&fit=crop&w=800&q=80",
      statusPonto: "Comprado / Ativo",
      observacoes: "Impacto BS: 346.618 pessoas | Impacto Mensal: 742.752 pessoas.",
    },
    {
      id: "PONTO-BULLOS-120",
      fornecedorId: "FORN-BULLOS",
      codigoIdentificador: "BULLOS-120A",
      nomeLocal: "Av. Noide Cerqueira (Após Shopping Aliança)",
      tipoFormato: "Outdoor Lona 9x3m (Triplo)",
      praca: "Feira de Santana",
      bairro: "SIM",
      endereco: "Av. Noide Cerqueira, sentido BR-324",
      latitude: -12.2685,
      longitude: -38.9250,
      fotoLocalUrl: "https://images.unsplash.com/photo-1572945553120-2130471643f3?auto=format&fit=crop&w=800&q=80",
      statusPonto: "Comprado / Ativo",
      observacoes: "Pontos 120A, 120B e 120C. Impacto: até 372.253 pessoas.",
    },
    {
      id: "PONTO-BULLOS-003021",
      fornecedorId: "FORN-BULLOS",
      codigoIdentificador: "BULLOS-3021",
      nomeLocal: "Av. Presidente Dutra (Após Igreja dos Capuchinhos)",
      tipoFormato: "Outdoor Lona 9x3m",
      praca: "Feira de Santana",
      bairro: "Capuchinhos",
      endereco: "Av. Presidente Dutra, sentido Salvador",
      latitude: -12.2645,
      longitude: -38.9550,
      fotoLocalUrl: "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80",
      statusPonto: "Comprado / Ativo",
      observacoes: "Impacto: 479.697 pessoas por bi-semana. Entrada e saída principal da cidade.",
    },
    {
      id: "PONTO-BULLOS-37",
      fornecedorId: "FORN-BULLOS",
      codigoIdentificador: "BULLOS-37",
      nomeLocal: "Anel de Contorno (Av. Eduardo Fróes da Mota - Próx. Correios)",
      tipoFormato: "Outdoor Lona 9x3m",
      praca: "Feira de Santana",
      bairro: "Lagoa Grande",
      endereco: "Av. Eduardo Fróes da Mota, sentido Cidade Nova / UEFS",
      latitude: -12.2470,
      longitude: -38.9420,
      fotoLocalUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
      statusPonto: "Comprado / Ativo",
      observacoes: "Impacto récorde: 601.240 pessoas por bi-semana. Fluxo pesado de universitários.",
    },

    // VITRINE OUTDOOR
    {
      id: "PONTO-VITRINE-SMTT",
      fornecedorId: "FORN-VITRINE",
      codigoIdentificador: "VITRINE-SMTT",
      nomeLocal: "Shopping Boulevard (Muro da SMTT / Estacionamento)",
      tipoFormato: "Outdoor Lona 9x3m Iluminado",
      praca: "Feira de Santana",
      bairro: "Coronel José Pinto",
      endereco: "R. Cel. José Pinto, em frente ao Shopping Boulevard",
      latitude: -12.2515,
      longitude: -38.9515,
      fotoLocalUrl: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80",
      statusPonto: "Comprado / Ativo",
      observacoes: "Tabela: R$ 1.600,00 lona / R$ 1.500,00 papel. Iluminação noturna de alto destaque.",
    },
    {
      id: "PONTO-VITRINE-NOIDE-MAIOR",
      fornecedorId: "FORN-VITRINE",
      codigoIdentificador: "VITRINE-NOIDE-MEGA",
      nomeLocal: "Av. Noide Cerqueira - Placa Especial 12,20x4m",
      tipoFormato: "Outdoor Mega Lona (12,20 x 4,00m) Iluminado",
      praca: "Feira de Santana",
      bairro: "SIM",
      endereco: "Av. Noide Cerqueira, sentido SIM",
      latitude: -12.2690,
      longitude: -38.9180,
      fotoLocalUrl: "https://images.unsplash.com/photo-1572945553120-2130471643f3?auto=format&fit=crop&w=800&q=80",
      statusPonto: "Disponível / Mapeado",
      observacoes: "Placa gigante de alto impacto no vetor de maior crescimento da cidade. Tabela R$ 1.600,00.",
    },
    {
      id: "PONTO-VITRINE-AMELIA-RODRIGUES",
      fornecedorId: "FORN-VITRINE",
      codigoIdentificador: "VITRINE-BR324-DUPLA",
      nomeLocal: "BR-324 (Próx. Amélia Rodrigues - Placa Dupla Rodoviária)",
      tipoFormato: "Outdoor Duplo 18x3m Iluminado",
      praca: "Feira de Santana / Rodovia",
      bairro: "BR-324",
      endereco: "BR-324, sentido Feira de Santana",
      latitude: -12.3800,
      longitude: -38.7500,
      fotoLocalUrl: "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80",
      statusPonto: "Disponível / Mapeado",
      observacoes: "Placa Dupla rodoviária com iluminação. Tabela: R$ 3.200,00 lona por BS. Impacto de todo fluxo Salvador -> Feira.",
    },

    // HENKLEY PUBLICIDADE (TELAS INDOOR)
    {
      id: "PONTO-HENKLEY-CIRCUITO-FSA",
      fornecedorId: "FORN-HENKLEY",
      codigoIdentificador: "HENKLEY-REDE-45",
      nomeLocal: "Rede Feira de Santana (45 Telas em 35 Locais)",
      tipoFormato: "Telas Digitais Indoor (TVs Full HD)",
      praca: "Feira de Santana",
      bairro: "Circuito Multibairros (Centro, Santa Mônica, SIM, Kalilândia)",
      endereco: "Clínicas, Academias, Restaurantes e Centros Médicos de Feira",
      latitude: -12.2570,
      longitude: -38.9600,
      fotoLocalUrl: "https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?auto=format&fit=crop&w=800&q=80",
      statusPonto: "Comprado / Ativo",
      observacoes: "418.950 pessoas impactadas/mês. 35.100 inserções mensais. Custo/mês: R$ 1.100 no plano semestral.",
    },

    // GIRLAN LED
    {
      id: "PONTO-GIRLAN-LED-F01",
      fornecedorId: "FORN-GIRLAN-LED",
      codigoIdentificador: "GIRLAN-LED-F01",
      nomeLocal: "Painel de LED Digital (Circuito FSA - Ponto F01)",
      tipoFormato: "Painel de LED 6,00 x 3,00m",
      praca: "Feira de Santana",
      bairro: "Centro / Maria Quitéria",
      endereco: "Av. Maria Quitéria x Av. Getúlio Vargas",
      latitude: -12.2580,
      longitude: -38.9580,
      fotoLocalUrl: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80",
      statusPonto: "Disponível / Mapeado",
      observacoes: "810 inserções diárias em alta resolução. Permite rotação de múltiplos vídeos para UNEF e UNIFAN.",
    },
  ];

  console.log(`Inserindo ${pontosReais.length} pontos físicos reais e homologados...`);
  for (const p of pontosReais) {
    await db.insert(pontosFisicos).values(p).onConflictDoUpdate({
      target: pontosFisicos.id,
      set: p,
    });
  }

  console.log("✅ Catalogação e banco de dados atualizados com sucesso!");
}

seedRealData().catch(console.error);
